Update reusable-ros-tooling-source-build.yml

diff --git a/.github/workflows/reusable-ros-tooling-source-build.yml b/.github/workflows/reusable-ros-tooling-source-build.yml
--- a/.github/workflows/reusable-ros-tooling-source-build.yml
+++ b/.github/workflows/reusable-ros-tooling-source-build.yml
@@ -69,13 +69,15 @@ jobs:
           path: ${{ env.repo_path }}
 
       # Run the generator and output the results to a file with retry logic.
-      - name: Use rosinstall_generator to get all dependencies
+      #- name: Use rosinstall_generator to get all dependencies
+      #  run: |
+      #    for i in {1..5}; do
+      #      rosinstall_generator ${{ steps.package_list_action.outputs.package_list }} --rosdistro ${{ inputs.ros_distro }} \
+      #      --deps-only --deps --upstream-development > /tmp/deps.repos && break || echo "retry #${i} .." && sleep 60;
+      #    done
+      - name: Use .repos file from repo
         run: |
-          for i in {1..5}; do
-            rosinstall_generator ${{ steps.package_list_action.outputs.package_list }} --rosdistro ${{ inputs.ros_distro }} \
-            --deps-only --deps --upstream-development > /tmp/deps.repos && break || echo "retry #${i} .." && sleep 60;
-          done
-
+          cp ${{ env.repo_path }}/my_repo.repos /tmp/deps.repos
       - uses: ros-tooling/action-ros-ci@0.4.5
         with:
           target-ros2-distro: ${{ inputs.ros_distro }}
